config/routes.rb
WarszawaHotel::Application.routes.draw do

  scope "(:locale)" do
    devise_for :users
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  get 'order/order_room'

  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)" do

    get "/articles", to: 'articles#list'
    get '/articles/:article_path', to: 'articles#item', as: :source_article_item

    match "rooms/:room_id/order", to: 'order#order_room', as: :order_specified_room, via: [:post, :get]
    get "/rooms/:id/order", to: 'order#order_room_form', as: :order_specified_room_form

    get "/rooms/order", to: 'order#order_room_form', as: :order_room_form
    post "/rooms/order", to: 'order#order_room', as: :order_room

    post '/order', to: 'contact#create_message', as: :source_send_message

    get 'about-hotel', to: 'about#hotel', as: :source_about_hotel, defaults: {page_id: 5}

    get 'rooms', to: 'about#rooms', as: :source_about_rooms, defaults: {page_id: 10}

    get 'prices', to: 'about#prices', as: :source_about_prices, defaults: {page_id: 11}

    get 'services', to: 'services#index', as: :source_services

    get 'restaurant', to: 'about#restaurant', as: :source_restaurant

    get 'contact-us', to: 'contact#index', as: :source_contact

    get '/order', to: 'contact#create_message', as: :source_order

    root to: 'home#index'
  end

  DynamicRouter.load

  get "*path", to: 'error#not_found', defaults: { error_code: 404 }

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :name, :email, :phone, :message
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def order_room_form
    @order_room_form_object = RoomOrder.new

    @is_specified_room = params[:id].to_i >= 1
    @specified_room = Room.where(id: params[:id])
    if @specified_room.respond_to?(:first) && @specified_room.respond_to?(:count) && @specified_room.count > 0
      @specified_room = @specified_room.first
    else
      @specified_room = nil
    end

    if !@is_specified_room || true
      @available_rooms = Room.where(published: 't').order('id desc')
    end

    #render layout: 'popup', template: 'order/order_room_form'
    render layout: 'ajax', template: 'order/order_room_form'
  end

  def order_room

    order = RoomOrder.create
    rooms_order_param = params['room_order']
    order.name = rooms_order_param['name']
    order.phone = rooms_order_param['phone']
    order.email = rooms_order_param['email']
    order.message = rooms_order_param['message']



    order.room = Room.find(params['room_id']) if rooms_order_param['room']
    order.save

    OrderMailer.create_message(order).deliver

    if !params['ajax']
      #render template: 'contact/original_index'
    else
      render inline: 'ok'
    end
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/order_room_form.html.erb
<div id="order-form-wrapper">
<!--<form action="<%# order_room_path %>" method="post"  >-->
  <!--<%# hidden_field_tag :email_page_portlet_url, @email_page_portlet_url %>-->
  <!--<%# f.cms_error_messages %>-->
  <!--<div class="s12 push-contact-us-form contact-inline-min">-->
    <!--<label for="Вас звати:">Вас звати:</label>-->
    <!--<input type="text" name="name" placeholder="Константин Константинопольскій" id="UserName" class="clear-contact-inputs s user-name contact-inline-min-inputs" />-->
    <!--<label for="Ваш номер телефону:">Ваш номер телефону:</label>-->
    <!--<input type="text" name="phone" placeholder="+38 (098) 511 77 73" id="UserPhone" class="clear-contact-inputs s user-phone contact-inline-min-inputs" />-->
    <!--<label for="Ваш e-mail:">Ваш e-mail:</label>-->
    <!--<input type="text" name="email" placeholder="konstantin.kost@gmail.com" id="UserEmail" class="clear-contact-inputs s user-email contact-inline-min-inputs" />-->

  <!--</div>-->
  <!--<div class="s12 push-contact-us-form contact-inline-min">-->
    <!--<label for="Текст Вашого повідомлення:">Текст Вашого повідомлення:</label>-->
    <!--<textarea name="message" placeholder="Ми піклуємося про те, щоб кожен гість отримав лише якісний та сучасний сервіс, що є для нас найкращою рекомендацією та компліментом." id="UserMsg" class="clear-contact-inputs s contact-text width1200 width-standart" />-->
  <!--</div>-->
  <!--<div class="s12 submit-area"><input type="submit" name="" value="" class="submit-button" id="btn-submit"></div>-->
<!--</form>-->

<style>
  /*body{
      padding: 0;
      margin: 0;
      background: url("/assets/main-bg-pattern-1.jpg") repeat transparent;
  }*/

  #order-form-wrapper{
      padding: 0;
      margin: 0;
      background: url("/assets/main-bg-pattern-1.jpg") repeat transparent;
  }
  .form-section{
      height: 470px;
      overflow: hidden;
      margin: 0;
  }

  .form-section.specified-room-order-form-section{
      height: 375px;
  }



  #room-order-form{
      margin: 0;
  }

  .contact-inline-min{
      width: 340px !important;
  }

  .contact-inline-min.message{
      width: 768px !important;
  }

  .contact-inline-min.message textarea{
      height: 280px;
  }



</style>
<div class="form-section<%= " specified-room-order-form-section" if false %>">

<div class="s12" id="msg-header"><h2 class="contact-h1-second"><%= t('partials.order-form.title') %></h2></div>
<div class="clearfix"></div>
<%= form_for @order_room_form_object, :url => order_room_path, :method=>'post', html: {id: 'room-order-form', class: "room-order-form#{" specified-room-order-form" if @is_specified_room == true}"} do |f| %>
    <%# hidden_field_tag :email_page_portlet_url, @email_page_portlet_url %>
    <%# f.cms_error_messages %>
    <div class="s12 push-contact-us-form contact-inline-min">
      <% if true %>
          <label for="room-select"><%= t('partials.form.fields.room.label') %></label>
          <select id="room-select" name="room_order[room]" data-error-message="<%= t('partials.form.fields.room.error-message') %>">
            <option value="0"><%= t('partials.form.fields.room.null-text') %></option>
            <% @available_rooms.each do |room| %>
                <option value="<%= room.id %>" <%= "selected" if @specified_room.respond_to?(:id) && room.id == @specified_room.id %> ><%= room.name %></option>
            <% end %>
          </select>
      <% end %>
      <label for="UserName"><%= t('partials.form.fields.name.label') %></label>
      <%= f.text_field :name, :placeholder => t('partials.form.fields.name.placeholder'), :id => "UserName", :class => "clear-contact-inputs s user-name contact-inline-min-inputs", :"data-error-message" => t('partials.form.fields.name.error-message') %>
      <label for="UserPhone"><%= t('partials.form.fields.phone.label') %></label>
      <%= f.text_field :phone, :placeholder => t('partials.form.fields.phone.placeholder'), :id => "UserPhone", :class => "clear-contact-inputs s user-phone contact-inline-min-inputs", :"data-error-message" => t('partials.form.fields.phone.error-message') %>
      <label for="UserEmail"><%= t('partials.form.fields.email.label') %></label>
      <%= f.text_field :email, :placeholder => t('partials.form.fields.email.placeholder'), :id => "UserEmail", :class => "clear-contact-inputs s user-email contact-inline-min-inputs", :"data-error-message" => t('partials.form.fields.email.error-message') %>

    </div>
    <div class="s12 push-contact-us-form contact-inline-min message">
      <label for="UserMsg"><%= t('partials.form.fields.message.label') %></label>
      <%= f.text_area :message, :placeholder => t('partials.form.fields.message.placeholder'), :id => "UserMsg", :class => "clear-contact-inputs s contact-text width1200 width-standart", :"data-error-message" => t('partials.form.fields.message.error-message') %>
    </div>
    <div class="s12 submit-area">
      <!--<input type="submit" name="" value="" class="submit-button" id="btn-submit">-->
      <span class="brand-button brand-button-submit">
        <span class="button-label"><%= t('partials.order-button') %></span>
        <input type="submit" name="submit" value="" class="submit-button" id="btn-submit">

      </span>
    </div>
<% end %>
</div>

</div>