config/routes.rb
WarszawaHotel::Application.routes.draw do

  scope "(:locale)" do
    devise_for :users
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  get 'order/order_room'

  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)" do

    get "/articles", to: 'articles#list'
    get '/articles/:article_path', to: 'articles#item', as: :source_article_item

    match "rooms/:room_id/order", to: 'order#order_room', as: :order_specified_room, via: [:post, :get]
    get "/rooms/:id/order", to: 'order#order_room_form', as: :order_specified_room_form

    get "/rooms/order", to: 'order#order_room_form', as: :order_room_form
    post "/rooms/order", to: 'order#order_room', as: :order_room

    post '/order', to: 'contact#create_message', as: :source_send_message

    get 'about-hotel', to: 'about#hotel', as: :source_about_hotel, defaults: {page_id: 5}

    get 'rooms', to: 'about#rooms', as: :source_about_rooms, defaults: {page_id: 10}

    get 'prices', to: 'about#prices', as: :source_about_prices, defaults: {page_id: 11}

    get 'services', to: 'services#index', as: :source_services

    get 'restaurant', to: 'about#restaurant', as: :source_restaurant

    get 'contact-us', to: 'contact#index', as: :source_contact

    get '/order', to: 'contact#create_message', as: :source_order

    root to: 'home#index'
  end

  DynamicRouter.load

  get "*path", to: 'error#not_found', defaults: { error_code: 404 }

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def hotel
    @title = 'Про готель //Готель львів//Готель варшава//Готелі львова//Львів готель'
    @meta_description = ''
    @meta_keywords = ''

    @about_page = Pages::AboutPage.first

  end

  def restaurant
    @title = 'РЕСТОРАН //Готель львів//Готель варшава//Готелі львова//Львів готель'
    @meta_description = ''
    @meta_keywords = ''

    @restaurant_page = Pages::Restaurant.first
  end

  def rooms
    @title = 'Номери //Готель львів//Готель варшава//Готелі львова//Львів готель'
    @meta_description = ''
    @meta_keywords = ''

    @rooms_page = Pages::RoomsList.first
    @rooms = Room.where(published: 't').order('id desc')

  end

  def prices
    @title = 'Ціни //Готель львів//Готель варшава//Готелі львова//Львів готель'
    @meta_description = ''
    @meta_keywords = ''

    @rooms = Room.where(published: 't').order('id desc')

    render template: 'about/db_prices'
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/_hotel_gallery.html.erb
<% if @about_page.about_page_gallery_images.count > 0 %>
<div class="s12" id="about-gallery"><h2 class="br-h"><%= t('pages.about.photo-gallery-section.title') %></h2></div>
<script type="text/javascript">
    $(document).ready(function() {
        $(".fancy-me-mate").fancybox();
    });
</script>

<% @about_page.about_page_gallery_images.each do |image| %>

<div class="s3 about-gallery-full-width about-gallery-margin">
  <a href="<%= image.image.about_page_large.url %>" class="fancy-me-mate about-gallery-img" rel="fancy-about-gallery-items">
    <img alt="" class="br about-gallery-img" src="<%= image.image.about_page_thumb.url %>" />
  </a>
</div>
<% end %>

<% end %>

app/views/about/_rooms_list.html.erb
<% @rooms.each do |room| %>
    <div class="service-bg-each s12 " id="sr<%= room.id %>">
      <div class="s5  hide-me-if-im-small service-no-margin">
        <img alt="" class="br" src="<%= room.avatar.room_avatar.url %>" />
      </div>
      <div class="s7 hide-me-if-im-small">
        <h2 id="no-pad">
          <img alt="&gt;" class="h1-mr" src="/assets/h1-mr.png" /><%= room.name %>
        </h2>
        <div class="services-full-descr">
          <%= raw room.full_description %>
        </div>
        <% room.room_gallery_images.each do |image| %>
            <a href="<%= image.image.room_large.url %>" class="service-img-margin hide-me-if-im-small fancy-me" rel="sr<%= room.id %>">
              <img alt="" class="br" src="<%= image.image.room_thumb.url %>" style="color: white !important;" />
            </a>
        <% end %>

        <div class="order">
          <a data-fancybox-type="iframe" href="<%= order_room_form_path(id: item.id, locale: I18n.locale) %>">Замовити</a>
        </div>
      </div>
      <!-- SHOW ME UP IF IM SMALL -->
      <div class="s12 show-me-if-im-small"><h2><img alt="&gt;" class="h1-mr" src="/assets/h1-mr.png" /><%= room.name %></h2></div>
      <div class="s6 show-me-if-im-small size-up-first-img">
        <img alt="" class="br" src="<%= room.avatar.room_avatar.url %>" />
      </div>
      <% if room.room_gallery_images.count > 0 %>
          <div class="s6 show-me-if-im-small size-up-last-img">
            <% room.room_gallery_images.each_with_index do |image, index| %>
                <a href="<% image.image.room_large.url %>" class="service-img-margin fancy-me " rel="sr<%= room.id %>">
                  <img alt="" class="br service-margin-me<%= " service-img-last" if index == room.room_gallery_images.count - 1 %>" src="<%= image.image.room_thumb.url %>" style="color: white !important;" />
                </a>
            <% end %>
          </div>
      <% end %>
      <div class="s12 show-me-if-im-small">
        <p class="services-full-descr">
          <%= raw room.full_description %>
        </p>
      </div>
      <!-- /SHOW ME UP IF IM SMALL -->
    </div>
<% end %>

app/views/about/_show_me_rooms.html.erb
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $(".fancy-me").fancybox({
            openEffect  : 'elastic',
            closeEffect : 'elastic',
            nextEffect : 'fade',
            prevEffect : 'fade'
        });

//        $(".order a").fancybox({
//            //maxWidth  : 1195, // 640
//            maxHeight : 820,
//            fitToView : false,
//            //width   : '70%',
//            height    : '100%',
//            autoSize  : false,
//            closeClick  : false,
//            openEffect  : 'none',
//            closeEffect : 'none',
//            padding: 0,
//            afterLoad : function(obj1, obj2){
//                OBJ1 = obj1
//                OBJ2 = obj2
//                $(".fancybox-wrap").addClass("room-form-popup").addClass('specified-room-form-popup');
//
//                var $iframe = $('.fancybox-iframe')
//                var $body = $iframe.contents().find('body')
//                var $textarea = $body.find('textarea')
//                $textarea = $('#fancybox-content iframe').contents().find('textarea')
//                alert('hello: ' + $("textarea").attr('placeholder'))
//
//
//                MY_CONTENT = $iframe.contents().find('body')
//
//
//                $textarea.click(function(){
//                    $(this).css({backgroundColor: 'red'})
//                    console.log('hello')
//                })
//            }
//        });
    });
</script>
<style>
    .order{
        margin-top: 40px;
        margin-bottom: 10px;
    }
    .order a{
        /*font-size: 20px;*/
        /*font-style: italic;*/
        /*border-bottom: 1px solid rgba(91, 44, 22, 0);*/
        /*text-decoration: none !important;*/
        -webkit-transition: 0.35s ease-out all;
        -moz-transition: 0.35s ease-out all;
        -ms-transition: 0.35s ease-out all;
        -o-transition: 0.35s ease-out all;
        transition: 0.35s ease-out all;
    }

    .order a:hover{
        /*border-bottom: 1px solid rgba(91, 44, 22, 1);*/
    }


</style>

<% @rooms.each do |item| %>
    <!-- ROOMS DISPLAY LINE UP -->
    <div class="service-bg-each s12 " id="sr<%= item.id %>">
      <div class="s5 <%= cycle("", "service-second") %> hide-me-if-im-small service-no-margin">
        <% [item.avatar].first(1).each do |avatar| %>
            <%= image_tag(avatar.room_avatar.url, :alt => "", :class => "br") %>
        <% end %>
      </div>
      <div class="s7 hide-me-if-im-small">
        <h2 id="no-pad">
          <%= image_tag("h1-mr.png", :alt => ">", :class => "h1-mr") %><%= item.translations_by_locale[I18n.locale].name %>
        </h2>
        <div class="services-full-descr">
          <%= item.translations_by_locale[I18n.locale].full_description.html_safe %>
        </div>
        <% item.room_gallery_images.each do |image| %>
            <%= link_to(image_tag(image.image.room_thumb.url, :alt => "", :class => "br", :style => "color: white !important;"), image.image.room_large.url, :class => "service-img-margin hide-me-if-im-small fancy-me", :rel => "sr#{item.id}") %>
        <% end %>

        <div class="order">
          <!--<a data-fancybox-type="iframe" href="<%# order_room_form_path(id: item.id, locale: I18n.locale) %>">Замовити</a>-->
          <a data-fancybox-type="iframe" data-room-id="<%= item.id %>" href="<%= order_specified_room_form_path(id: item.id, locale: I18n.locale) %>" class="brand-button modal-link"><span><%= t('pages.rooms-list.order-button.label') %></span></a>
        </div>
      </div>
      <!-- SHOW ME UP IF IM SMALL -->
      <div class="s12 show-me-if-im-small"><h2><%= image_tag("h1-mr.png", :alt => ">", :class => "h1-mr") %><%= item.translations_by_locale[I18n.locale].name %></h2></div>
      <div class="s6 show-me-if-im-small size-up-first-img">
        <% [item.avatar].first(1).each do |img| %>
            <%= image_tag(img.room_avatar.url, :alt => "", :class => "br") %>
        <% end %>
      </div>
      <div class="s6 show-me-if-im-small size-up-last-img">
        <% item.room_gallery_images.each_with_index do |image, index| %>
            <%= link_to(image_tag(image.image.room_thumb.url, :alt => "", :class => "br service-margin-me", :style => "color: white !important;"), image.image.room_large.url, :class => "service-img-margin fancy-me#{" service-img-last" if index == item.room_gallery_images.count}", :rel => "sr#{item.id}") %>
        <% end %>

      </div>
      <div class="s12 show-me-if-im-small"><p class="services-full-descr"><%= item.translations_by_locale[I18n.locale].full_description.html_safe %></p></div>
      <!-- /SHOW ME UP IF IM SMALL -->
    </div>
    <!-- /ROOMS DISPLAY LINE UP -->
<% end %>

app/views/about/db_prices.html.erb
<script>
    $(document).ready(function(){
        $('.iframe').fancybox(function(){
            console.log('up here');
        });
    });
</script>
<a href="" class="iframe"></a>
<section id="wr" class="container">
  <div id="bring-me-up">
    <article id="about-us-page" class="row">
      <div class="s3 about-full-width ">
        <%= render partial: "partials/about_menu" %>
      </div>
      <div class="s9 about-full-width about-fix-width">
        <%# container :prices_table %>
        <style>
            table{
                width: 100%;
            }
            thead{
                width: 100%;
                background: url('assets/form-background_03.jpg') repeat rgba(0, 0, 0, 0) !important;
                border: 1px solid rgb(177, 173, 170) !important;
                padding: 5px 0;
            }
            .f-td{
                width: 40%;
                padding: 5px 0;
            }
            .s-td{
                width: 15%;
                padding: 5px 0;
            }
            .th-td{
                width: 22,5%;
                padding: 5px 0;
            }
            .fo-td{
                width: 22,5%;
                padding: 5px 0;
            }
            .f-td p,
            .s-td p,
            .th-td p,
            .fo-td p{
                margin-left: 10px;
                margin-bottom: 2px;
            }
            .f-td p i,
            .s-td p i,
            .th-td p i,
            .fo-td p i{
                color: #53381b;
                font-size: 12px;
            }
            .p-cent{
                text-align: center;
            }
            .descr-price{
                margin-top: 30px;
                margin-bottom: 280px;
            }

            .descr-price p{
                margin-bottom: 6px;
            }

            .price-p{
                font-size: 20px;
            }

            tr.transparent{
                background: transparent;
            }

            tr.colored{
                background: #cab8a9;
            }
        </style>
        <table>
          <thead>
          <tr>
            <td class="f-td"><p><%= t('pages.prices.table.columns.room-category') %></p> </td>
            <td class="s-td"><p><%= t('pages.prices.table.columns.quantity') %></p></td>
            <td class="th-td"><p><%= t('pages.prices.table.columns.price') %></p></td>
            <td class="fo-td"><p><%= t('pages.prices.table.columns.extra-bed') %></p></td>
          </tr>
          </thead>
          <tbody>
          <% @rooms.each_with_index do |room, room_index| %>
              <tr class="<%= room_index % 2 == 0?  "transparetn" : "colored" %>">
                <td class="f-td"><p><%= room.translations_by_locale[I18n.locale].name %></p></td>
                <td class="s-td"><p class="p-cent"><%= room.quantity %></p></td>
                <td class="th-td"><p class="p-cent price-p"><%= room.price_per_night %></p></td>
                <td class="fo-td"><p class="p-cent"><%= room.extra_bed_price %></p></td>
              </tr>
          <% end %>



          </tbody>
          <tfoot>
          </tfoot>
        </table>
        <div class="descr-price">
          <p><%= t('pages.prices.text.p1') %></p>
          <br class="clearfix" />
          <p><%= t('pages.prices.text.p2') %></p>

          <br class="clearfix" />
          <p><%= t('pages.prices.text.p3') %></p>

          <br class="clearfix" />
          <p><%= t('pages.prices.text.p4') %></p>

        </div>
      </div>
      <br class="clearfix" />
      <div id="pushup" style="height: 320px;">&nbsp;</div>
    </article>
    <div class="push-crown row">
      <div class="s5 br-h">&nbsp;</div>
      <div class="s2" style="text-align: center;"><%= image_tag("crown-end.png") %></div>
      <div class="s5 br-h crown-last-width">&nbsp;</div>
    </div>
  </div>
</section>

app/views/about/hotel.html.erb
<section id="wr" class="container">
  <div id="bring-me-up">
    <article id="about-us-page" class="row">
      <div class="s3 about-full-width ">
        <%= render partial: "partials/about_menu" %>
      </div>
      <div class="s9 about-full-width about-fix-width">
        <div>
          <h1 class="about-h1"><%= t('pages.about.page-title') %></h1>

          <iframe src="http://embed.virtual.ua/booking_hotels-4255" width="100%" height="400" frameborder="no" scrolling="no" class="br about-main-img"></iframe>
          <%#= image_tag("about-main-img.jpg", :class => "br about-main-img") %>
        </div>
        <div class="about-header">
        <%# container :aboutheader %>
          <%= @about_page.text_under_slider %>
        </div>
        <div class="about-header-sub1"><%# container :aboutheadersub1 %></div>
      </div>
      <br class="clearfix" />
      <div class="s6 about-full-width about-fix-width get-me-right">
        <blockquote style="margin-top: 130px;">
          <em class="begin">«</em>
          <div class="about-header-blockquote">
          <%# container :aboutheaderblockquote %>
            <p>
              <em>
                <%= @about_page.quote %>
              </em>
            </p>
          </div>
          <em class="end">»</em>
        </blockquote>
      </div>
      <div class="s6 about-full-width about-fix-width get-me-right">
        <div class="about-header-sub2">
        <%# container :aboutheadersub2 %>
          <%= @about_page.text %>
        </div>
      </div>

      <%# container :aboutgallery %>
      <%= render partial: 'about/hotel_gallery' %>

    </article>

  </div>
  <div class="push-crown row">
    <div class="s5 br-h">&nbsp;</div>
    <div class="s2" style="text-align: center;"><%= image_tag("crown-end.png") %></div>
    <div class="s5 br-h crown-last-width">&nbsp;</div>
  </div>
</section>

app/views/about/prices.html.erb
<script>
    $(document).ready(function(){
        $('.iframe').fancybox(function(){
            console.log('up here');
        });
    });
</script>
<a href="" class="iframe"></a>
<section id="wr" class="container">
  <div id="bring-me-up">
    <article id="about-us-page" class="row">
      <div class="s3 about-full-width ">
        <%= render partial: "partials/about_menu" %>
      </div>
      <div class="s9 about-full-width about-fix-width">
        <%# container :prices_table %>
        <style>
            table{
                width: 100%;
            }
            thead{
                width: 100%;
                background: url('assets/form-background_03.jpg') repeat rgba(0, 0, 0, 0) !important;
                border: 1px solid rgb(177, 173, 170) !important;
                padding: 5px 0;
            }
            .f-td{
                width: 40%;
                padding: 5px 0;
            }
            .s-td{
                width: 15%;
                padding: 5px 0;
            }
            .th-td{
                width: 22,5%;
                padding: 5px 0;
            }
            .fo-td{
                width: 22,5%;
                padding: 5px 0;
            }
            .f-td p,
            .s-td p,
            .th-td p,
            .fo-td p{
                margin-left: 10px;
                margin-bottom: 2px;
            }
            .f-td p i,
            .s-td p i,
            .th-td p i,
            .fo-td p i{
                color: #53381b;
                font-size: 12px;
            }
            .p-cent{
                text-align: center;
            }
            .descr-price{
                margin-top: 30px;
                margin-bottom: 280px;
            }

            .descr-price p{
                margin-bottom: 6px;
            }

            .price-p{
                font-size: 20px;
            }

            tr.transparent{
                background: transparent;
            }

            tr.colored{
                background: #cab8a9;
            }
        </style>
        <table>
          <thead>
          <tr>
            <td class="f-td"><p>Категорія номеру</p> <p><i>Room category</i></p></td>
            <td class="s-td"><p>Кількість</p> <p><i>Quantity</i></p></td>
            <td class="th-td"><p>Ціна за добу, грн.</p> <p><i>Rate per night, UAH</i></p></td>
            <td class="fo-td"><p>Додаткове ліжко, грн.</p> <p><i>Extra bed, UAH</i></p></td>
          </tr>
          </thead>
          <tbody>
          <tr class="transparetn">
            <td class="f-td"><p>Двомісний стандартний з двома ліжками</p> <p><i>Standard Twin</i></p></td>
            <td class="s-td"><p class="p-cent">19</p></td>
            <td class="th-td"><p class="p-cent price-p">350,00</p></td>
            <td class="fo-td"><p class="p-cent">100,00</p></td>
          </tr>
          <tr class="colored">
            <td class="f-td"><p>Двомісний стандартний</p> <p><i>Double Standard</i></p></td>
            <td class="s-td"><p class="p-cent">13</p></td>
            <td class="th-td"><p class="p-cent price-p">350,00</p></td>
            <td class="fo-td"><p class="p-cent">100,00</p></td>
          </tr>
          <tr class="transparent">
            <td class="f-td"><p>Комфорт</p> <p><i>Comfort</i></p></td>
            <td class="s-td"><p class="p-cent">2</p></td>
            <td class="th-td"><p class="p-cent price-p">450,00</p></td>
            <td class="fo-td"><p class="p-cent">100,00</p></td>
          </tr>
          <tr class="colored">
            <td class="f-td"><p>Напівлюкс</p> <p><i>Junior Suite</i></p></td>
            <td class="s-td"><p class="p-cent">1</p></td>
            <td class="th-td"><p class="p-cent price-p">550,00</p></td>
            <td class="fo-td"><p class="p-cent">&mdash;</p></td>
          </tr>
          <tr class="transparent">
            <td class="f-td"><p>Люкс</p> <p><i>Suite</i></p></td>
            <td class="s-td"><p class="p-cent">6</p></td>
            <td class="th-td"><p class="p-cent price-p">750,00</p></td>
            <td class="fo-td"><p class="p-cent">&mdash;</p></td>
          </tr>
          <tr class="colored">
            <td class="f-td"><p>Номер для молодят</p> <p><i>Wedding Junior Suite</i></p></td>
            <td class="s-td"><p class="p-cent">1</p></td>
            <td class="th-td"><p class="p-cent price-p">550,00</p></td>
            <td class="fo-td"><p class="p-cent">&mdash;</p></td>
          </tr>
          </tbody>
          <tfoot>
          </tfoot>
        </table>
        <div class="descr-price">
          <p>Розрахункова година в готелі 12:00; година заїзду 14:00, сніданок 8:00 – 10:00</p>
          <p><i>Check-out time 12:00, check-in time 14:00, breakfast 8:00 – 10:00</i></p>
          <br class="clearfix" />
          <p>Ціна номера включає: Wi-Fi ІНТЕРНЕТ, паркінг,, камеру схову, доставку кореспонденції, виклик таксі, податки.</p>
          <p><i>The price includes: WI-FI INTERNET ACCESS, parking,, correspondence delivery, taxi ordering and taxes.</i></p>
          <br class="clearfix" />
          <p>При виїзді протягом 12 годин після розрахункової години плата за проживання береться ще за половину доби.</p>
          <p><i>In case the room is vacated 12 hours after check-out hour, the fee is charged for additional <sup>½</sup> price.</i></p>
          <br class="clearfix" />
          <p>Гарантований ранковий заїзд – половина вартості номеру за добу.</p>
          <p><i>Guaranteed early check-in -1/2 of room rate.</i></p>
        </div>
      </div>
      <br class="clearfix" />
      <div id="pushup" style="height: 320px;">&nbsp;</div>
    </article>
    <div class="push-crown row">
      <div class="s5 br-h">&nbsp;</div>
      <div class="s2" style="text-align: center;"><%= image_tag("crown-end.png") %></div>
      <div class="s5 br-h crown-last-width">&nbsp;</div>
    </div>
  </div>
</section>

app/views/about/restaurant.html.erb
<section id="wr" class="container">
  <div id="bring-me-up">
    <article id="about-us-page" class="row">
      <div class="s3 about-full-width">
        &nbsp;
      </div>
      <div class="s9 about-full-width">
        <%= raw @restaurant_page.content %>
      </div>
    </article>
  </div>
  <div class="push-crown row">
    <div class="s5 br-h">&nbsp;</div>
    <div class="s2" style="text-align: center;"><%= image_tag("crown-end.png") %></div>
    <div class="s5 br-h crown-last-width">&nbsp;</div>
  </div>
</section>

app/views/about/rooms.html.erb
<section id="wr" class="container">
  <div id="bring-me-up">
    <article id="about-us-page" class="row">
      <div class="s3 about-full-width">
        <%= render partial: "partials/about_menu" %>
      </div>
      <div class="s9 about-full-width">
        <div>
          <h1 class="about-h1"><%= t('pages.rooms-list.page-title') %></h1>
          <%= image_tag("rooms_new.jpg", :class => "br about-main-img") %>
        </div>
        <p class="about-header">
        <%# container :roomsheader %>
          <%= raw @rooms_page.intro_text %>
        </p>
        <p class="about-header-sub1"><%# container :roomsheadersub1 %></p>
      </div>

      <div class="s3 about-full-width">&nbsp;</div>

      <%# container :roomsheadersub4 %>

      <%= render partial: 'about/show_me_rooms' %>



    </article>

  </div>
  <div class="push-crown row">
    <div class="s5 br-h">&nbsp;</div>
    <div class="s2" style="text-align: center;"><%= image_tag("crown-end.png") %></div>
    <div class="s5 br-h crown-last-width">&nbsp;</div>
  </div>
</section>

app/views/about/test.html.erb
<div class = "s3 w-logo"> <img alt = "" src = "/ aktywa /" / W-logo.png> </div>

<div class = "S1 W-l">  </div>

<div class = "s8 w-msg">
  <h2> witamy w kompleksie Hotel-Restaurant & laquo, Warszawa ! </h2>

  <p class = "W-P1"> & laquo, Warszawa   Ta szlachetna elegancja i nowoczesny serwis, będzie doświadczenie od pierwszej do ostatniej minuty wakacjach. </p>

  <p class = "W-P2"> Jesteśmy przekonani, że nasz zespół specjalistów sprawi, że wizyta niezapomnianą podróż do miejsca opieki, bezwzględnego jakości i żywych doznań. Dla każdego odwiedzającego  Warszawie , jest jego największa wartość, która tworzy nową historię dziś </P>.
  <- <P class = "W-p3"> <a href="/contact-us"> Zobacz mapę dojazdu </a> lub <a href="/about-hotel"> dowiedzieć się więcej o hotelu </> </p> ->

  <p class = "W-P3 link-linia"> <a href="/about-hotel"> szczegóły hotelu </a> <a href="http://warszawa.virtual.ua"> wirtualna </> <a href="/contact-us"> Nasza lokalizacja </a> </p>
</div>