config/routes.rb
WarszawaHotel::Application.routes.draw do

  scope "(:locale)" do
    devise_for :users
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  get 'order/order_room'

  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)" do

    get "/articles", to: 'articles#list'
    get '/articles/:article_path', to: 'articles#item', as: :source_article_item

    match "rooms/:room_id/order", to: 'order#order_room', as: :order_specified_room, via: [:post, :get]
    get "/rooms/:id/order", to: 'order#order_room_form', as: :order_specified_room_form

    get "/rooms/order", to: 'order#order_room_form', as: :order_room_form
    post "/rooms/order", to: 'order#order_room', as: :order_room

    post '/order', to: 'contact#create_message', as: :source_send_message

    get 'about-hotel', to: 'about#hotel', as: :source_about_hotel, defaults: {page_id: 5}

    get 'rooms', to: 'about#rooms', as: :source_about_rooms, defaults: {page_id: 10}

    get 'prices', to: 'about#prices', as: :source_about_prices, defaults: {page_id: 11}

    get 'services', to: 'services#index', as: :source_services

    get 'restaurant', to: 'about#restaurant', as: :source_restaurant

    get 'contact-us', to: 'contact#index', as: :source_contact

    get '/order', to: 'contact#create_message', as: :source_order

    root to: 'home#index'
  end

  DynamicRouter.load

  get "*path", to: 'error#not_found', defaults: { error_code: 404 }

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @title = 'Контакти //Готель львів//Готель варшава//Готелі львова//Львів готель'
    @meta_description = ''
    @meta_keywords = ''

    render template: 'contact/original_index'
  end

  def create_message
    @title = 'Контакти //Готель львів//Готель варшава//Готелі львова//Львів готель'
    @meta_description = ''
    @meta_keywords = ''

    order = Order.create
    order.name = params['email_message']['user_name']
    order.phone = params['email_message']['user_phone']
    order.email = params['email_message']['user_mail']
    order.message = params['email_message']['user_msg']
    order.save

    #render inline: params.inspect

    OrderMailer.create_message(order).deliver

    if !params['ajax']

      render template: 'contact/original_index'
    else
      render inline: 'ok'
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/_form.html.erb
  <form  accept-charset="UTF-8" action="<%= source_send_message_path(locale: I18n.locale) %>" class="new_email_message contact-form" id="new_email_message" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="be5zeUpB6NKop92TASWpqbckW32ZrMBdLTl38tV12ag=" /></div>
    <input id="email_page_portlet_url" name="email_page_portlet_url" type="hidden" value="http://warszawa-hotel.com.ua/contact-us" />

    <div class="s12 push-contact-us-form contact-inline-min">
      <label for="Вас звати:"><%= t('partials.form.fields.name.label') %></label>
      <input data-error-message="<%= t('partials.form.fields.name.error-message') %>" class="clear-contact-inputs s user-name contact-inline-min-inputs" id="UserName" name="email_message[user_name]" placeholder="<%= t('partials.form.fields.name.placeholder') %>" size="30" type="text" />
      <label for="Ваш номер телефону:"><%= t('partials.form.fields.phone.label') %></label>
      <input data-error-message="<%= t('partials.form.fields.phone.error-message') %>"  class="clear-contact-inputs s user-phone contact-inline-min-inputs" id="UserPhone" name="email_message[user_phone]" placeholder="<%= t('partials.form.fields.phone.placeholder') %>" size="30" type="text" />
      <label for="Ваш e-mail:"><%= t('partials.form.fields.email.label') %></label>
      <input data-error-message="<%= t('partials.form.fields.email.error-message') %>"  class="clear-contact-inputs s user-email contact-inline-min-inputs" id="UserEmail" name="email_message[user_mail]" placeholder="<%= t('partials.form.fields.email.placeholder') %>" size="30" type="text" />

    </div>
    <div class="s12 push-contact-us-form contact-inline-min message">
      <label for="Текст Вашого повідомлення:"><%= t('partials.form.fields.message.label') %></label>
      <textarea data-error-message="<%= t('partials.form.fields.message.error-message') %>" class="clear-contact-inputs s contact-text width1200 width-standart" cols="40" id="UserMsg" name="email_message[user_msg]" placeholder="<%= t('partials.form.fields.message.placeholder') %>" rows="20"></textarea>
    </div>
    <!--<div class="s12 submit-area"><input type="submit" name="" value="" class="submit-button" id="btn-submit"></div>-->
    <div class="s12 submit-area">
      <span class="brand-button brand-button-submit">
        <span class="button-label"><%= t('partials.contact-form-button') %></span>
        <input type="submit" name="submit" value="" class="submit-button" id="btn-submit">
      </span>
    </div>
  </form></div>

app/views/contact/create_message.html.erb
<h1>Contact#create_message</h1>
<p>Find me in app/views/contact/create_message.html.erb</p>